### ISSUE TITLE
Erroneous removal of flexbox

### ISSUE THREAD

**Issue by Immortalin** [peterbe/mincss#37]
The following css keep on getting removed even though they are necessary.

```css
.login{
	display: flex;
	justify-content: center;
	align-items: center;
}

```
