### ISSUE TITLE
Remove unused @font-face

### ISSUE THREAD

**Issue by igitur** [peterbe/mincss#49]
Hi

Great tool. It works great except that it doesn't remove unused CSS items, e.g. 

```css
@font-face {
  font-family: 'Lato';
  font-style: normal;
  font-weight: 400;
  src: local('Lato Regular'), local('Lato-Regular'), url(data:font/woff;base64,d09GR... <snip/> ...AisA) format('woff');
}
```

As you can see, the font data is encoded and embedded, which makes the spreadsheets massive (blame https://github.com/grammarly !).
